import { NextRequest, NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin";
import { logServerError } from "@/lib/api/errors";

export async function POST(req: NextRequest) {
  const { authorized, user } = await requireAdmin();
  // Allow development mode convenience if user is logged in
  if (!authorized && !(process.env.NODE_ENV === "development" && user)) {
    return NextResponse.json({ error: "Unauthorized admin access" }, { status: 401 });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      {
        error: "GEMINI_API_KEY is not configured in environment variables (.env.local). Please set GEMINI_API_KEY.",
      },
      { status: 500 }
    );
  }

  try {
    const { imageUrl } = await req.json();
    if (!imageUrl || typeof imageUrl !== "string") {
      return NextResponse.json(
        { error: "Image URL is required" },
        { status: 400 }
      );
    }

    // Fetch image data from the provided URL
    let base64Data: string;
    let mimeType: string = "image/jpeg";

    if (imageUrl.startsWith("data:")) {
      const parts = imageUrl.split(",");
      const matches = imageUrl.match(/^data:(image\/[a-zA-Z+]+);base64,/);
      if (matches && matches[1]) {
        mimeType = matches[1];
      }
      base64Data = parts[1];
    } else {
      const imgRes = await fetch(imageUrl);
      if (!imgRes.ok) {
        return NextResponse.json(
          { error: `Failed to fetch image from URL: ${imgRes.statusText}` },
          { status: 400 }
        );
      }
      const contentType = imgRes.headers.get("content-type");
      if (contentType && contentType.startsWith("image/")) {
        mimeType = contentType;
      }
      const arrayBuffer = await imgRes.arrayBuffer();
      base64Data = Buffer.from(arrayBuffer).toString("base64");
    }

    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey}`;

    const prompt = `Analyze this shirt product image and generate marketing details.
Return a JSON object with EXACTLY these fields:
- "name": A catchy, high-converting product title for a shirt (e.g. "Vintage Linen Casual Shirt").
- "description": A compelling 2-3 sentence description detailing fabric texture, style, pattern, and versatility.
- "category": A single short category name (e.g. "casual", "formal", "tshirts", "graphic-tees", "oversized").

Respond with pure JSON only, without any markdown formatting or extra text.`;

    const requestBody = {
      contents: [
        {
          parts: [
            { text: prompt },
            {
              inline_data: {
                mime_type: mimeType,
                data: base64Data,
              },
            },
          ],
        },
      ],
      generationConfig: {
        response_mime_type: "application/json",
        temperature: 0.4,
      },
    };

    const res = await fetch(geminiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      const errText = await res.text();
      logServerError("Gemini API request failed", errText);
      return NextResponse.json(
        { error: "Gemini API error. Check GEMINI_API_KEY or request payload." },
        { status: 502 }
      );
    }

    const resData = await res.json();
    const generatedText =
      resData?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      return NextResponse.json(
        { error: "No response text generated by Gemini" },
        { status: 500 }
      );
    }

    const parsedData = JSON.parse(generatedText);
    return NextResponse.json({
      success: true,
      data: {
        name: parsedData.name ?? "",
        description: parsedData.description ?? "",
        category: parsedData.category ?? "",
      },
    });
  } catch (err: unknown) {
    logServerError("AI product details generation failed", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to generate AI details" },
      { status: 500 }
    );
  }
}
